[happyserv]
enabled = true
logpath = /var/log/auth.log
maxretry = 5
bantime = 3600
findtime = 600

[happyserv-nginx]
enabled = true
port = http,https
filter = nginx-http-auth
logpath = /var/log/nginx/error.log
maxretry = 10
bantime = 3600
findtime = 600

[happyserv-api]
enabled = true
port = http,https
filter = happyserv-api
logpath = /var/log/happyserv/api.log
maxretry = 10
bantime = 3600
findtime = 600

[happyserv-portal]
enabled = true
port = http,https
filter = happyserv-portal
logpath = /var/log/happyserv/portal.log
maxretry = 10
bantime = 3600
findtime = 600

[DEFAULT]
banaction = ufw
banaction_allports = ufw
ignoreip = 127.0.0.1/8 ::1
